### ISSUE TITLE
Alternative text/captions for images

### ISSUE THREAD

**Issue by Lextuga007** [nhsengland/nhs-r-reporting#38]
This might take a bit of work, particularly to describe some of the screenshots in things like https://nhsengland.github.io/nhs-r-reporting/tutorials/rstudio-git.html but could alt text or captions be added and used in the future? Thanks 🙂

**Comment by craig-shenton** [comment]
Good point, I will add it as a requirement of contributing to the site https://nhsengland.github.io/nhs-r-reporting/contribute.html

Will try to chatGPT it!
